# Wire up travis
language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=cover

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

notifications:
  email:
    - repoze-checkins@lists.repoze.org
